Document: dnremoteserver
Title: Debian dnremoteserver Manual
Author: <insert document author here>
Abstract: This manual describes what dnremoteserver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/dnremoteserver/dnremoteserver.sgml.gz

Format: postscript
Files: /usr/share/doc/dnremoteserver/dnremoteserver.ps.gz

Format: text
Files: /usr/share/doc/dnremoteserver/dnremoteserver.text.gz

Format: HTML
Index: /usr/share/doc/dnremoteserver/html/index.html
Files: /usr/share/doc/dnremoteserver/html/*.html
